// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIp-vSZPODQ241-WH2IDJmQahMSkUvEqk',
    appId: '1:465236063032:web:0ed245da2c2eceb0a487cd',
    messagingSenderId: '465236063032',
    projectId: 'quizzle-f5e63',
    authDomain: 'quizzle-f5e63.firebaseapp.com',
    storageBucket: 'quizzle-f5e63.appspot.com',
    measurementId: 'G-56S2174X5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiDkHwn_CAl5_3cOKcI53DsG-VBY9X78I',
    appId: '1:465236063032:android:cc7398d253dee983a487cd',
    messagingSenderId: '465236063032',
    projectId: 'quizzle-f5e63',
    storageBucket: 'quizzle-f5e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_VVlKyI2v4l95U31-1Kzg8NrUwfe2Jfc',
    appId: '1:465236063032:ios:f670fff784a69ac6a487cd',
    messagingSenderId: '465236063032',
    projectId: 'quizzle-f5e63',
    storageBucket: 'quizzle-f5e63.appspot.com',
    iosClientId: '465236063032-a5gabm898t3l9l4vdvpvjk37re4llrdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzledemo',
  );
}
